# アイドル一覧のハッシュテーブル
# {'アイドル名': id}

# idは発音のアルファベット表記、FamilynameLastname
# 並び順はアイマスCGWiki準拠になるように頑張る
# アルファベット表記は原則カードの表記準拠
# こちらは正規表現でマッチ「後」のハッシュテーブルなので、制御文字のエスケープは不要
exports.table = {

  '前川みく': 'MaekawaMiku'
  '前川みく+': 'MaekawaMiku+'
  '赤西瑛梨華': 'AkanishiErika'
  '赤西瑛梨華+': 'AkanishiErika+'
  '松原早耶': 'MatsubaraSaya'
  '松原早耶+': 'MatsubaraSaya+'
  '相原雪乃': 'AiharaYukino'
  '相原雪乃+': 'AiharaYukino+'
  ' 宮本フレデリカ': 'MiyamotoFrederica'
  ' 宮本フレデリカ+': 'MiyamotoFrederica+'

# 4ページ
  '小早川紗枝': 'KobayakawaSae'
  '小早川紗枝+': 'KobayakawaSae+'
  '西園寺琴歌': 'SaionjiKotoka'
  '西園寺琴歌+': 'SaionjiKotoka+'
  '双葉杏': 'FutabaAnzu'
  '双葉杏+': 'FutabaAnzu+'
  '楊菲菲': 'YaoFueiFuei'
  '楊菲菲+': 'YaoFueiFuei+'
  '桃井あずき': 'MomoiAzuki'
  '桃井あずき+': 'MomoiAzuki+'
  '涼宮星花': 'SuzumiyaSeika'
  '涼宮星花+': 'SuzumiyaSeika+'
  '月宮雅': 'TsukimiyaMiyabi'
  '月宮雅+': 'TsukimiyaMiyabi+'
  '兵藤レナ': 'HyodoRena'
  '兵藤レナ+': 'HyodoRena+'

# 5ページ
  '道明寺歌鈴': 'DomyojiKarin'
  '道明寺歌鈴+': 'DomyojiKarin+'
  '高槻やよい': 'TakatsukiYayoi'
  '高槻やよい+': 'TakatsukiYayoi+'
  '菊地真': 'KikuchiMakoto'
  '菊地真+': 'KikuchiMakoto+'
  '我那覇響': 'GanahaHibiki'
  '我那覇響+': 'GanahaHibiki+'
  '柳清良': 'YanagiKiyora'
  '柳清良+': 'YanagiKiyora+'
  '［聖夜］小日向美穂': 'SeiyaKohinataMiho'
  '［聖夜］小日向美穂+': 'SeiyaKohinataMiho+'
  '井村雪菜': 'ImuraSetsuna'
  '井村雪菜+': 'ImuraSetsuna+'
  '［新春］道明寺歌鈴': 'ShinshunDomyojiKarin'
  '［新春］道明寺歌鈴+': 'ShinshunDomyojiKarin+'

# 6ページ
  '日下部若葉': 'KusakabeWakaba'
  '日下部若葉+': 'KusakabeWakaba+'
  '榊原里美': 'SakakibaraSatomi'
  '榊原里美+': 'SakakibaraSatomi+'
  '輿水幸子': 'KoshimizuSachiko'
  '輿水幸子+': 'KoshimizuSachiko+'
  '安斎都': 'AnzaiMiyako'
  '安斎都+': 'AnzaiMiyako+'
  '浅野風香': 'AsanoFuka'
  '浅野風香+': 'AsanoFuka+'
  '大西由里子': 'OnishiYuriko'
  '大西由里子+': 'OnishiYuriko+'
  '［バレンタイン］緒方智絵里': 'ValentineOgataChieri'
  '［バレンタイン］緒方智絵里+': 'ValentineOgataChieri+'
  '安部菜々': 'AbeNana'
  '安部菜々+': 'AbeNana+'

# 7ページ
  '工藤忍': 'KudoShinobu'
  '工藤忍+': 'KudoShinobu+'
  '栗原ネネ': 'KuriharaNene'
  '栗原ネネ+': 'KuriharaNene+'
  '［ひな祭り］福山舞': 'HinamatsuriFukuyamaMai'
  '［ひな祭り］福山舞+': 'HinamatsuriFukuyamaMai'
  '［純粋奏者］水本ゆかり': 'JunsuisoshaMizumotoYukari'
  '［純粋奏者］水本ゆかり+': 'JunsuisoshaMizumotoYukari+'
  '古賀小春': 'KogaKoharu'
  '古賀小春+': 'KogaKoharu+'
  '［お花見］中野有香': 'OhanamiNakanoYuka'
  '［お花見］中野有香+': 'OhanamiNakanoYuka+'
  '［制服コレクション］楊菲菲': 'SeifukucollectionYaoFueiFuei'
  '［制服コレクション］楊菲菲+': 'SeifukucollectionYaoFueiFuei+'
  '［沖縄元気っ娘］我那覇響': 'OkinawagenkikkoGanahaHibiki'
  '［沖縄元気っ娘］我那覇響+': 'OkinawagenkikkoGanahaHibiki+'
  '［王子様な女子］菊地真': 'OjisamanajoshiKikuchiMakoto'
  '［王子様な女子］菊地真+': 'OjisamanajoshiKikuchiMakoto+'
  '［セクシーキャット］前川みく': 'SexycatMaekawaMiku'
  '［セクシーキャット］前川みく+': 'SexycatMaekawaMiku+'

# 8ページ
  '［秘めた輝き］原田美世': 'HimetakagayakiHaradaMiyo'
  '［秘めた輝き］原田美世+': 'HimetakagayakiHaradaMiyo+'
  '［天才ロボ少女］池袋晶葉': 'TensairoboshojoIkebukuroAkiha'
  '［天才ロボ少女］池袋晶葉+': 'TensairoboshojoIkebukuroAkiha+'
  '［艶娘大作戦］桃井あずき': 'YoendaisakusenMomoiAzuki'
  '［艶娘大作戦］桃井あずき+': 'YoendaisakusenMomoiAzuki'
  '［だらだら妖精］双葉杏': 'DaradarayoseiFutabaAnzu'
  '［だらだら妖精］双葉杏+': 'DaradarayoseiFutabaAnzu+'
  '［戦国姫］小日向美穂+': 'SengokuhimeKohinataMiho+'
  '［薔薇色お姫様］櫻井桃華': 'BarairoohimesamaSakuraiMomoka'
  '［薔薇色お姫様］櫻井桃華+': 'BarairoohimesamaSakuraiMomoka+'
  '［ふわふわスマイル］三村かな子': 'FuwafuwasmileMimuraKanako'
  'SRかな子': 'FuwafuwasmileMimuraKanako'
  '［ふわふわスマイル］三村かな子+': 'FuwafuwasmileMimuraKanako+'
  '［制服ベージュ］天海春香': 'SeifukubeigeAmamiHaruka'
  '招待春香': 'SeifukubeigeAmamiHaruka'

# 9ページ
  '［普通の女の子］天海春香': 'FutsunoonnanokoAmamiHaruka'
  '［普通の女の子］天海春香+': 'FutsunoonnanokoAmamiHaruka'
  '［制服グリーン］高槻やよい': 'SeifukugreenTakatsukiYayoi'
  '招待やよい': 'SeifukugreenTakatsukiYayoi'

# 10ページ
  '［元気120%］高槻やよい': 'Genki120percentTakatsukiYayoi'
  '［元気120%］高槻やよい+': 'Genki120percentTakatsukiYayoi+'

  
# クール
# 3ページ
  'ヘレン': 'Helen'
  'ヘレン+': 'Helen+'
  '松永涼': 'MatsunagaRyo'
  '松永涼+': 'MatsunagaRyo+'
  '小室千奈美': 'KomuroChinami'
  '小室千奈美+': 'KomuroChinami+'
  '高峯のあ': 'TakamineNoa'
  '高峯のあ+': 'TakamineNoa+'

# 4ページ
  '高垣楓': 'TakagakiKaede'
  '高垣楓+': 'TakagakiKaede+'
  '神崎蘭子': 'KanzakiRanko'
  '神崎蘭子+': 'KanzakiRanko+'
  '伊集院惠': 'IjuinMegumi'
  '伊集院惠+': 'IjuinMegumi+'
  '柊志乃': 'HiragiShino'
  '柊志乃+': 'HiragiShino+'
  '北条加蓮': 'HojoKaren'
  '北条加蓮+': 'HojoKaren+'
  'ケイト': 'Kate'
  'ケイト+': 'Kate+'
  '瀬名詩織': 'SenaShiori'
  '瀬名詩織+': 'SenaShiori+'
  '綾瀬穂乃香': 'AyaseHonoka'
  '綾瀬穂乃香+': 'AyaseHonoka+'

# 5ページ
  '佐城雪美': 'SajoYukimi'
  '佐城雪美+': 'SajoYukimi+'
  '如月千早': 'KisaragiChihaya'
  '如月千早+': 'KisaragiChihaya'
  '三浦あずさ': 'MiuraAzusa'
  '三浦あずさ+': 'MiuraAzusa+'
  '秋月律子': 'AkizukiRitsuko'
  '秋月律子+': 'AkizukiRitsuko+'
  '四条貴音': 'ShijoTakane'
  '四条貴音+': 'ShijoTakane+'
  '篠原礼': 'ShinoharaRei'
  '篠原礼+': 'ShinoharaRei+'
  '［聖夜］神谷奈緒': 'SeiyaKamiyaNao'
  '［聖夜］神谷奈緒+': 'SeiyaKamiyaNao+'
  '［新春］東郷あい': 'ShinshunTogoAi'
  '［新春］東郷あい+': 'ShinshunTogoAi+'

# 6ページ
  '和久井留美': 'WakuiRumi'
  '和久井留美+': 'WakuiRumi+'
  '吉岡沙紀': 'YoshiokaSaki'
  '吉岡沙紀+': 'YoshiokaSaki+'
  '梅木音葉': 'UmekiOtoha'
  '梅木音葉+': 'UmekiOtoha+'
  '白坂小梅': 'ShirasakaKoume'
  '白坂小梅+': 'ShirasakaKoume+'
  '岸部彩華': 'KishibeAyaka'
  '岸部彩華+': 'KishibeAyaka+'
  '氏家むつみ': 'UjiieMutsumi'
  '氏家むつみ+': 'UjiieMutsumi+'
  '西川保奈美': 'NishikawaHonami'
  '西川保奈美+': 'NishikawaHonami+'
  '［バレンタイン］多田李衣菜': 'ValentineTadaRina'
  '［バレンタイン］多田李衣菜+': 'ValentineTadaRina+'

# 7ページ
  '成宮由愛': 'NarumiyaYume'
  '成宮由愛+': 'NarumiyaYume+'
  '［ひな祭り］藤居朋': 'HinamatsuriFujiTomo'
  '［ひな祭り］藤居朋+': 'HinamatsuriFujiTomo+'
  '［眼鏡マジック］上条春菜': 'MeganemagicKamijoHaruna'
  '［眼鏡マジック］上条春菜+': 'MeganemagicKamijoHaruna+'
  '［制服コレクション］北条加蓮': 'SeifukucollectionHojoKaren'
  '［制服コレクション］北条加蓮+': 'SeifukucollectionHojoKaren'
  '［孤高の歌姫］如月千早': 'KokonoutahimeKisaragiChihaya'
  '［孤高の歌姫］如月千早+': 'KokonoutahimeKisaragiChihaya+'
  '［皆のお姉さん］三浦あずさ': 'MinnanoonesanMiuraAzusa'
  '［皆のお姉さん］三浦あずさ+': 'MinnanoonesanMiuraAzusa+'
  '［ニュージェネレーション］渋谷凛': 'NewgenerationShibuyaRin'
  '［ニュージェネレーション］渋谷凛+': 'NewgenerationShibuyaRin+'
  '［博識子女］古澤頼子': 'HakushikishijoFurusawaYoriko'
  '［博識子女］古澤頼子+': 'HakushikishijoFurusawaYoriko+'
  '［聖なる乙女］望月聖': 'SeinaruotomeMochizukiHijiri'
  '［聖なる乙女］望月聖+': 'SeinaruotomeMochizukiHijiri+'

# 8ページ
  '［エステル衣装］三浦あずさ+': 'EstherishoMiuraAzusa+'
  '［幸運の女神］鷹富士茄子': 'KounnomegamiTakafujiNasuko'
  '［幸運の女神］鷹富士茄子+': 'KounnomegamiTakafujiNasuko+'
  '［銀色の王女］四条貴音': 'GinironoojoShijoTakane'
  '［銀色の王女］四条貴音+': 'GinironoojoShijoTakane+'
  '［ピュアハート］綾瀬穂乃香': 'PureheartAyaseHonoka'
  '［ピュアハート］綾瀬穂乃香+': 'PureheartAyaseHonoka+'
  '［天使な堕天使］神崎蘭子': 'TenshinadatenshiKanzakiRanko'
  '［天使な堕天使］神崎蘭子+': 'TenshinadatenshiKanzakiRanko+'
  '［寡黙の女王］高峯のあ': 'KamokunojooTakamineNoa'
  '［寡黙の女王］高峯のあ+': 'KamokunojooTakamineNoa+'
  '［制服ブルー］如月千早': 'SeifukublueKisaragiChihaya'
  '招待千早': 'SeifukublueKisaragiChihaya'
  '［瑠璃の歌姫］如月千早': 'RurinoutahimeKisaragiChihaya'
  '［瑠璃の歌姫］如月千早+': 'RurinoutahimeKisaragiChihaya+'
  '［神秘の女神］高垣楓': 'ShimpinomegamiTakagakiKaede'
  '［神秘の女神］高垣楓+': 'ShimpinomegamiTakagakiKaede+'

# パッション
# 3ページ
  '相葉夕美': 'AibaYumi'
  '相葉夕美+': 'AibaYumi+'
  '野々村そら': 'NonomuraSora'
  '野々村そら+': 'NonomuraSora+'
  '浜川愛結奈': 'HamakawaAyuna'
  '浜川愛結奈+': 'HamakawaAyuna+'
  '若林智香': 'WakabayashiTomoka'
  '若林智香+': 'WakabayashiTomoka+'
  '城ヶ崎美嘉': 'JougasakiMika'
  '城ヶ崎美嘉+': 'JougasakiMika+'

# 4ページ
  '城ヶ崎莉嘉': 'JougasakiRika'
  '城ヶ崎莉嘉+': 'JougasakiRika+'
  '仙崎恵磨': 'SenzakiEma'
  '仙崎恵磨+': 'SenzakiEma+'
  '日野茜': 'HinoAkane'
  '日野茜+': 'HinoAkane+'
  '諸星きらり': 'MoroboshiKirari'
  '諸星きらり+': 'MoroboshiKirari+'
  '十時愛梨': 'TotokiAiri'
  '十時愛梨+': 'TotokiAiri+'
  'ナターリア': 'Natalia'
  'ナターリア+': 'Natalia+'
  '相馬夏美': 'SomaNatsumi'
  '相馬夏美+': 'SomaNatsumi+'
  '槙原志保': 'MakiharaShiho'
  '槙原志保+': 'MakiharaShiho+'
  '萩原雪歩': 'HagiwaraYukiho'
  '萩原雪歩+': 'HagiwaraYukiho+'

# 5ページ
  '双海亜美': 'FutamiAmi'
  '双海亜美+': 'FutamiAmi+'
  '双海真美': 'FutamiMami'
  '双海真美+': 'FutamiMami+'
  '星井美希': 'HoshiiMiki'
  '星井美希+': 'HoshiiMiki+'
  '向井拓海': 'MukaiTakumi'
  '向井拓海+': 'MukaiTakumi+'
  '水瀬伊織': 'MinaseIori'
  '水瀬伊織+': 'MinaseIori+'
  '［聖夜］ナターリア': 'SeiyaNatalia'
  '［聖夜］ナターリア+': 'SeiyaNatalia+'
  '［新春］龍崎薫': 'ShinshunRyuzakiKaoru'
  '［新春］龍崎薫+': 'ShinshunRyuzakiKaoru'
  '市原仁奈': 'IchiharaNina'
  '市原仁奈+': 'IchiharaNina'

# 6ページ
  '杉坂海': 'SugisakaUmi'
  '杉坂海+': 'SugisakaUmi+'
  '喜多日菜子': 'KitaHinako'
  '喜多日菜子+': 'KitaHinako+'
  '北川真尋': 'KitagawaMahiro'
  '北川真尋+': 'KitagawaMahiro+'
  'メアリー･コクラン': 'MaryCochran'
  'メアリー･コクラン+': 'MaryCochran+'
  '小松伊吹': 'KomatsuIbuki'
  '小松伊吹+': 'KomatsuIbuki+'
  '［バレンタイン］赤城みりあ': 'ValentineAkagiMiria'
  '［バレンタイン］赤城みりあ+': 'ValentineAkagiMiria+'
  '三好紗南': 'MiyoshiSana'
  '三好紗南+': 'MiyoshiSana+'

# 7ページ
  'キャシー･グラハム': 'CathyGraham'
  'キャシー･グラハム+': 'CathyGraham+'
  '［ひな祭り］上田鈴帆': 'HinamatsuriUedaSuzuho'
  '［ひな祭り］上田鈴帆+': 'HinamatsuriUedaSuzuho+'
  '難波笑美': 'NambaEmi'
  '難波笑美+': 'NambaEmi'
  '［高飛車お嬢様］水瀬伊織': 'TakabishaojosamaMinaseIori'
  '［高飛車お嬢様］水瀬伊織+': 'TakabishaojosamaMinaseIori+'
  '［臆病な天使］萩原雪歩': 'OkubyonatenshiHagiwaraYukiho'
  '［臆病な天使］萩原雪歩+': 'OkubyonatenshiHagiwaraYukiho+'
  '［小さな英雄］南条光': 'ChiisanaeiyuNanjoHikaru'
  '［小さな英雄］南条光+': 'ChiisanaeiyuNanjoHikaru+'
  '［聖夜の使者］イヴ・サンタクロース': 'SeiyanoshishaEveSantaclaus'
  '［聖夜の使者］イヴ・サンタクロース+': 'SeiyanoshishaEveSantaclaus+'
  '［ラブリープリンセス］諸星きらり': 'LovelyprincessMoroboshiKirari'
  '［ラブリープリンセス］諸星きらり+': 'LovelyprincessMoroboshiKirari+'
  '［スイートバレンタイン］十時愛梨': 'SweetvalentineTotokiAiri'
  '［スイートバレンタイン］十時愛梨+': 'SweetvalentineTotokiAiri+'

# 8ページ
  '［パワフル双子妹］双海亜美': 'PowerfulfutagoimotoFutamiAmi'
  '［パワフル双子妹］双海亜美+': 'PowerfulfutagoimotoFutamiAmi+'
  '［パワフル双子姉］双海真美': 'PowerfulfutagoaneFutamiMami'
  '［パワフル双子姉］双海真美+': 'PowerfulfutagoaneFutamiMami+'
  '［お転婆ひな娘］喜多見柚': 'OtembahinamusumeKitamiYuzu'
  '［お転婆ひな娘］喜多見柚+': 'OtembahinamusumeKitamiYuzu+'
  '［制服オレンジ］星井美希': 'SeifukuorangeHoshiiMiki'
  '招待美希': 'SeifukuorangeHoshiiMiki'
  '［才能無限大］星井美希': 'SainomugendaiHoshiiMiki'

# 9ページ
  '［才能無限大］星井美希+': 'SainomugendaiHoshiiMiki'
  'ベテラントレーナー': 'VeteranTrainer'
  'マスタートレーナー': 'MasterTrainer'

}


# アイドル一覧
# 正規表現に突っ込んで検索するので制御文字はエスケープすること
# ただし+,[,]だけは全部処理側でエスケープする仕様に変更したよ
# aliasも全部書くべしし
exports.list = [

  '前川みく'
  '前川みく+'
  '赤西瑛梨華'
  '赤西瑛梨華+'
  '松原早耶'
  '松原早耶+'
  '相原雪乃'
  '相原雪乃+'
  ' 宮本フレデリカ'
  ' 宮本フレデリカ+'

# 4ページ
  '小早川紗枝'
  '小早川紗枝+'
  '西園寺琴歌'
  '西園寺琴歌+'
  '双葉杏'
  '双葉杏+'
  '楊菲菲'
  '楊菲菲+'
  '桃井あずき'
  '桃井あずき+'
  '涼宮星花'
  '涼宮星花+'
  '月宮雅'
  '月宮雅+'
  '兵藤レナ'
  '兵藤レナ+'

# 5ページ
  '道明寺歌鈴'
  '道明寺歌鈴+'
  '高槻やよい'
  '高槻やよい+'
  '菊地真'
  '菊地真+'
  '我那覇響'
  '我那覇響+'
  '柳清良'
  '柳清良+'
  '［聖夜］小日向美穂'
  '［聖夜］小日向美穂+'
  '井村雪菜'
  '井村雪菜+'
  '［新春］道明寺歌鈴'
  '［新春］道明寺歌鈴+'

# 6ページ
  '日下部若葉'
  '日下部若葉+'
  '榊原里美'
  '榊原里美+'
  '輿水幸子'
  '輿水幸子+'
  '安斎都'
  '安斎都+'
  '浅野風香'
  '浅野風香+'
  '大西由里子'
  '大西由里子+'
  '［バレンタイン］緒方智絵里'
  '［バレンタイン］緒方智絵里+'
  '安部菜々'
  '安部菜々+'

# 7ページ
  '工藤忍'
  '工藤忍+'
  '栗原ネネ'
  '栗原ネネ+'
  '［ひな祭り］福山舞'
  '［ひな祭り］福山舞+'
  '［純粋奏者］水本ゆかり'
  '［純粋奏者］水本ゆかり+'
  '古賀小春'
  '古賀小春+'
  '［お花見］中野有香'
  '［お花見］中野有香+'
  '［制服コレクション］楊菲菲'
  '［制服コレクション］楊菲菲+'
  '［沖縄元気っ娘］我那覇響'
  '［沖縄元気っ娘］我那覇響+'
  '［王子様な女子］菊地真'
  '［王子様な女子］菊地真+'
  '［セクシーキャット］前川みく'
  '［セクシーキャット］前川みく+'

# 8ページ
  '［秘めた輝き］原田美世'
  '［秘めた輝き］原田美世+'
  '［天才ロボ少女］池袋晶葉'
  '［艶娘大作戦］桃井あずき'
  '［艶娘大作戦］桃井あずき+'
  '［だらだら妖精］双葉杏'
  '［だらだら妖精］双葉杏+'
  '［戦国姫］小日向美穂+'
  '［薔薇色お姫様］櫻井桃華'
  '［薔薇色お姫様］櫻井桃華+'
  '［ふわふわスマイル］三村かな子'
  'SRかな子'
  '［ふわふわスマイル］三村かな子+'
  '［制服ベージュ］天海春香'
  '招待春香'

# 9ページ
  '［普通の女の子］天海春香'
  '［普通の女の子］天海春香+'
  '［制服グリーン］高槻やよい'
  '招待やよい'

# 10ページ
  '［元気120%］高槻やよい'
  '［元気120%］高槻やよい+'

  
# クール
# 3ページ
  'ヘレン'
  'ヘレン+'
  '松永涼'
  '松永涼+'
  '小室千奈美'
  '小室千奈美+'
  '高峯のあ'
  '高峯のあ+'

# 4ページ
  '高垣楓'
  '高垣楓+'
  '神崎蘭子'
  '神崎蘭子+'
  '伊集院惠'
  '伊集院惠+'
  '柊志乃'
  '柊志乃+'
  '北条加蓮'
  '北条加蓮+'
  'ケイト'
  'ケイト+'
  '瀬名詩織'
  '瀬名詩織+'
  '綾瀬穂乃香'
  '綾瀬穂乃香+'

# 5ページ
  '佐城雪美'
  '佐城雪美+'
  '如月千早'
  '如月千早+'
  '三浦あずさ'
  '三浦あずさ+'
  '秋月律子'
  '秋月律子+'
  '四条貴音'
  '四条貴音+'
  '篠原礼'
  '篠原礼+'
  '［聖夜］神谷奈緒'
  '［聖夜］神谷奈緒+'
  '［新春］東郷あい'
  '［新春］東郷あい+'

# 6ページ
  '和久井留美'
  '和久井留美+'
  '吉岡沙紀'
  '吉岡沙紀+'
  '梅木音葉'
  '梅木音葉+'
  '白坂小梅'
  '白坂小梅+'
  '岸部彩華'
  '岸部彩華+'
  '氏家むつみ'
  '氏家むつみ+'
  '西川保奈美'
  '西川保奈美+'
  '［バレンタイン］多田李衣菜'
  '［バレンタイン］多田李衣菜+'

# 7ページ
  '成宮由愛'
  '成宮由愛+'
  '［ひな祭り］藤居朋'
  '［ひな祭り］藤居朋+'
  '［眼鏡マジック］上条春菜'
  '［眼鏡マジック］上条春菜+'
  '［制服コレクション］北条加蓮'
  '［制服コレクション］北条加蓮+'
  '［孤高の歌姫］如月千早'
  '［孤高の歌姫］如月千早+'
  '［皆のお姉さん］三浦あずさ'
  '［皆のお姉さん］三浦あずさ+'
  '［ニュージェネレーション］渋谷凛'
  '［ニュージェネレーション］渋谷凛+'
  '［博識子女］古澤頼子'
  '［博識子女］古澤頼子+'
  '［聖なる乙女］望月聖'
  '［聖なる乙女］望月聖+'

# 8ページ
  '［エステル衣装］三浦あずさ+'
  '［幸運の女神］鷹富士茄子'
  '［幸運の女神］鷹富士茄子+'
  '［銀色の王女］四条貴音'
  '［銀色の王女］四条貴音+'
  '［ピュアハート］綾瀬穂乃香'
  '［ピュアハート］綾瀬穂乃香+'
  '［天使な堕天使］神崎蘭子'
  '［天使な堕天使］神崎蘭子+'
  '［寡黙の女王］高峯のあ'
  '［寡黙の女王］高峯のあ+'
  '［制服ブルー］如月千早'
  '招待千早'
  '［瑠璃の歌姫］如月千早'
  '［瑠璃の歌姫］如月千早+'
  '［神秘の女神］高垣楓'
  '［神秘の女神］高垣楓+'

# パッション
# 3ページ
  '相葉夕美'
  '相葉夕美+'
  '野々村そら'
  '野々村そら+'
  '浜川愛結奈'
  '浜川愛結奈+'
  '若林智香'
  '若林智香+'
  '城ヶ崎美嘉'
  '城ヶ崎美嘉+'

# 4ページ
  '城ヶ崎莉嘉'
  '城ヶ崎莉嘉+'
  '仙崎恵磨'
  '仙崎恵磨+'
  '日野茜'
  '日野茜+'
  '諸星きらり'
  '諸星きらり+'
  '十時愛梨'
  '十時愛梨+'
  'ナターリア'
  'ナターリア+'
  '相馬夏美'
  '相馬夏美+'
  '槙原志保'
  '槙原志保+'
  '萩原雪歩'
  '萩原雪歩+'
  '双海亜美'
  '双海亜美+'
  '双海真美'
  '双海真美+'
  '星井美希'
  '星井美希+'
  '向井拓海'
  '向井拓海+'
  '水瀬伊織'
  '水瀬伊織+'
  '［聖夜］ナターリア'
  '［聖夜］ナターリア+'
  '［新春］龍崎薫'
  '［新春］龍崎薫+'
  '市原仁奈'
  '市原仁奈+'

# 6ページ
  '杉坂海'
  '杉坂海+'
  '喜多日菜子'
  '喜多日菜子+'
  '北川真尋'
  '北川真尋+'
  'メアリー･コクラン'
  'メアリー･コクラン+'
  '小松伊吹'
  '小松伊吹+'
  '［バレンタイン］赤城みりあ'
  '［バレンタイン］赤城みりあ+'
  '三好紗南'
  '三好紗南+'

# 7ページ
  'キャシー･グラハム'
  'キャシー･グラハム+'
  '［ひな祭り］上田鈴帆'
  '［ひな祭り］上田鈴帆+'
  '難波笑美'
  '難波笑美+'
  '［高飛車お嬢様］水瀬伊織'
  '［高飛車お嬢様］水瀬伊織+'
  '［臆病な天使］萩原雪歩'
  '［臆病な天使］萩原雪歩+'
  '［小さな英雄］南条光'
  '［小さな英雄］南条光+'
  '［聖夜の使者］イヴ・サンタクロース'
  '［聖夜の使者］イヴ・サンタクロース+'
  '［ラブリープリンセス］諸星きらり'
  '［ラブリープリンセス］諸星きらり+'
  '［スイートバレンタイン］十時愛梨'
  '［スイートバレンタイン］十時愛梨+'

# 8ページ
  '［パワフル双子妹］双海亜美'
  '［パワフル双子妹］双海亜美+'
  '［パワフル双子姉］双海真美'
  '［パワフル双子姉］双海真美+'
  '［お転婆ひな娘］喜多見柚'
  '［お転婆ひな娘］喜多見柚+'
  '［制服オレンジ］星井美希'
  '招待美希'
  '［才能無限大］星井美希'

# 9ページ
  '［才能無限大］星井美希+'
  'ベテラントレーナー'
  'マスタートレーナー'
]



# id一覧
exports.ids = [
# 3ページ目
  'MaekawaMiku'
  'MaekawaMiku+'
  'AkanishiErika'
  'AkanishiErika+'
  'MatsubaraSaya'
  'MatsubaraSaya+'
  'AiharaYukino'
  'AiharaYukino+'
  'MiyamotoFrederica'
  'MiyamotoFrederica+'
  'KobayakawaSae'
  'KobayakawaSae+'
  'SaionjiKotoka'
  'SaionjiKotoka+'
  'FutabaAnzu'
  'FutabaAnzu+'
  'YaoFueiFuei'
  'YaoFueiFuei+'
  'MomoiAzuki'
  'MomoiAzuki+'
  'SuzumiyaSeika'
  'SuzumiyaSeika+'
  'TsukimiyaMiyabi'
  'TsukimiyaMiyabi+'
  'HyodoRena'
  'HyodoRena+'

# 5ページ
  'DomyojiKarin'
  'DomyojiKarin+'
  'TakatsukiYayoi'
  'TakatsukiYayoi+'
  'KikuchiMakoto'
  'KikuchiMakoto+'
  'GanahaHibiki'
  'GanahaHibiki+'
  'YanagiKiyora'
  'YanagiKiyora+'
  'SeiyaKohinataMiho'
  'SeiyaKohinataMiho+'
  'ImuraSetsuna'
  'ImuraSetsuna+'
  'ShinshunDomyojiKarin'
  'ShinshunDomyojiKarin+'

# 6ページ
  'KusakabeWakaba'
  'KusakabeWakaba+'
  'SakakibaraSatomi'
  'SakakibaraSatomi+'
  'KoshimizuSachiko'
  'KoshimizuSachiko+'
  'AnzaiMiyako'
  'AnzaiMiyako+'
  'AsanoFuka'
  'AsanoFuka+'
  'OnishiYuriko'
  'OnishiYuriko+'
  'ValentineOgataChieri'
  'ValentineOgataChieri+'
  'AbeNana'
  'AbeNana+'

# 7ページ
  'KudoShinobu'
  'KudoShinobu+'
  'KuriharaNene'
  'KuriharaNene+'
  'HinamatsuriFukuyamaMai'
  'HinamatsuriFukuyamaMai+'
  'JunsuisoshaMizumotoYukari'
  'JunsuisoshaMizumotoYukari+'
  'KogaKoharu'
  'KogaKoharu+'
  'OhanamiNakanoYuka'
  'OhanamiNakanoYuka+'
  'SeifukucollectionYaoFueiFuei'
  'SeifukucollectionYaoFueiFuei+'
  'OkinawagenkikkoGanahaHibiki'
  'OkinawagenkikkoGanahaHibiki+'
  'OjisamanajoshiKikuchiMakoto'
  'OjisamanajoshiKikuchiMakoto+'
  'SexycatMaekawaMiku'
  'SexycatMaekawaMiku+'

# 8ページ
  'HimetakagayakiHaradaMiyo'
  'HimetakagayakiHaradaMiyo+'
  'TensairoboshojoIkebukuroAkiha'
  'TensairoboshojoIkebukuroAkiha+'
  'YoendaisakusenMomoiAzuki'
  'YoendaisakusenMomoiAzuki+'
  'DaradarayoseiFutabaAnzu'
  'DaradarayoseiFutabaAnzu+'
  'SengokuhimeKohinataMiho+'
  'BarairoohimesamaSakuraiMomoka'
  'BarairoohimesamaSakuraiMomoka+'
  'FuwafuwasmileMimuraKanako'
  'FuwafuwasmileMimuraKanako+'
  'SeifukubeigeAmamiHaruka'
  'FutsunoonnanokoAmamiHaruka'
  'FutsunoonnanokoAmamiHaruka+'
  'SeifukugreenTakatsukiYayoi'
  'Genki120percentTakatsukiYayoi'
  'Genki120percentTakatsukiYayoi+'

# クール
# 3ページ
  'Helen'
  'Helen+'
  'MatsunagaRyo'
  'MatsunagaRyo+'
  'KomuroChinami'
  'KomuroChinami+'
  'TakamineNoa'
  'TakamineNoa+'

# 4ページ
  'TakagakiKaede'
  'TakagakiKaede+'
  'KanzakiRanko'
  'KanzakiRanko+'
  'IjuinMegumi'
  'IjuinMegumi+'
  'HiragiShino'
  'HiragiShino+'
  'HojoKaren'
  'HojoKaren+'
  'Kate'
  'Kate+'
  'SenaShiori'
  'SenaShiori+'
  'AyaseHonoka'
  'AyaseHonoka+'

# 5ページ
  'SajoYukimi'
  'SajoYukimi+'
  'KisaragiChihaya'
  'KisaragiChihaya+'
  'MiuraAzusa'
  'MiuraAzusa+'
  'AkizukiRitsuko'
  'AkizukiRitsuko+'
  'ShijoTakane'
  'ShijoTakane+'
  'ShinoharaRei'
  'ShinoharaRei+'
  'SeiyaKamiyaNao'
  'SeiyaKamiyaNao+'
  'ShinshunTogoAi'
  'ShinshunTogoAi+'

# 6ページ
  'WakuiRumi'
  'WakuiRumi+'
  'YoshiokaSaki'
  'YoshiokaSaki+'
  'UmekiOtoha'
  'UmekiOtoha+'
  'ShirasakaKoume'
  'ShirasakaKoume+'
  'KishibeAyaka'
  'KishibeAyaka+'
  'UjiieMutsumi'
  'UjiieMutsumi+'
  'NishikawaHonami'
  'NishikawaHonami+'
  'ValentineTadaRina'
  'ValentineTadaRina+'

# 7ページ
  'NarumiyaYume'
  'NarumiyaYume+'
  'HinamatsuriFujiTomo'
  'HinamatsuriFujiTomo+'
  'MeganemagicKamijoHaruna'
  'MeganemagicKamijoHaruna+'
  'SeifukucollectionHojoKaren'
  'SeifukucollectionHojoKaren+'
  'KokonoutahimeKisaragiChihaya'
  'KokonoutahimeKisaragiChihaya+'
  'MinnanoonesanMiuraAzusa'
  'MinnanoonesanMiuraAzusa+'
  'NewgenerationShibuyaRin'
  'NewgenerationShibuyaRin+'
  'HakushikishijoFurusawaYoriko'
  'HakushikishijoFurusawaYoriko+'
  'SeinaruotomeMochizukiHijiri'
  'SeinaruotomeMochizukiHijiri+'

# 8ページ
  'EstherishoMiuraAzusa+'
  'KounnomegamiTakafujiNasuko'
  'KounnomegamiTakafujiNasuko+'
  'GinironoojoShijoTakane'
  'GinironoojoShijoTakane+'
  'PureheartAyaseHonoka'
  'PureheartAyaseHonoka+'
  'TenshinadatenshiKanzakiRanko'
  'TenshinadatenshiKanzakiRanko+'
  'KamokunojooTakamineNoa'
  'KamokunojooTakamineNoa+'
  'SeifukublueKisaragiChihaya'

# 9ページ
  'RurinoutahimeKisaragiChihaya'
  'RurinoutahimeKisaragiChihaya+'
  'ShimpinomegamiTakagakiKaede'
  'ShimpinomegamiTakagakiKaede+'

# パッション
# 3ページ
  'AibaYumi'
  'AibaYumi+'
  'NonomuraSora'
  'NonomuraSora+'
  'HamakawaAyuna'
  'HamakawaAyuna+'
  'WakabayashiTomoka'
  'WakabayashiTomoka+'
  'JougasakiMika'
  'JougasakiMika+'

# 4ページ
  'JougasakiRika'
  'JougasakiRika+'
  'SenzakiEma'
  'SenzakiEma+'
  'HinoAkane'
  'HinoAkane+'
  'MoroboshiKirari'
  'MoroboshiKirari+'
  'TotokiAiri'
  'TotokiAiri+'
  'Natalia'
  'Natalia+'
  'SomaNatsumi'
  'SomaNatsumi+'
  'MakiharaShiho'
  'MakiharaShiho+'
  'HagiwaraYukiho'
  'HagiwaraYukiho+'

# 5ページ
  'FutamiAmi'
  'FutamiAmi+'
  'FutamiMami'
  'FutamiMami+'
  'HoshiiMiki'
  'HoshiiMiki+'
  'MukaiTakumi'
  'MukaiTakumi+'
  'MinaseIori'
  'MinaseIori+'
  'SeiyaNatalia'
  'SeiyaNatalia+'
  'ShinshunRyuzakiKaoru'
  'ShinshunRyuzakiKaoru+'
  'IchiharaNina'
  'IchiharaNina+'

# 6ページ
  'SugisakaUmi'
 'SugisakaUmi+'
  'KitaHinako'
  'KitaHinako+'
  'KitagawaMahiro'
  'KitagawaMahiro+'
  'MaryCochran'
  'MaryCochran+'
  'KomatsuIbuki'
  'KomatsuIbuki+'
  'ValentineAkagiMiria'
  'ValentineAkagiMiria+'
  'MiyoshiSana'
  'MiyoshiSana+'

# 7ページ
  'CathyGraham'
  'CathyGraham+'
  'HinamatsuriUedaSuzuho'
  'HinamatsuriUedaSuzuho+'
  'NambaEmi'
  'NambaEmi+'
  'TakabishaojosamaMinaseIori'
  'TakabishaojosamaMinaseIori+'
  'OkubyonatenshiHagiwaraYukiho'
  'OkubyonatenshiHagiwaraYukiho+'
  'ChiisanaeiyuNanjoHikaru'
  'ChiisanaeiyuNanjoHikaru+'
  'SeiyanoshishaEveSantaclaus'
  'SeiyanoshishaEveSantaclaus+'
  'LovelyprincessMoroboshiKirari'
  'LovelyprincessMoroboshiKirari+'
  'SweetvalentineTotokiAiri'
  'SweetvalentineTotokiAiri+'

# 8ページ
  'PowerfulfutagoimotoFutamiAmi'
  'PowerfulfutagoimotoFutamiAmi+'
  'PowerfulfutagoaneFutamiMami'
  'PowerfulfutagoaneFutamiMami+'
  'OtembahinamusumeKitamiYuzu'
  'OtembahinamusumeKitamiYuzu+'
  'SeifukuorangeHoshiiMiki'
  'SainomugendaiHoshiiMiki'

# 9ページ
  'SainomugendaiHoshiiMiki+'
  'VeteranTrainer'
  'MasterTrainer'
]
