# アイドル一覧のハッシュテーブル
# {'アイドル名': id}

# idは発音のアルファベット表記、FamilynameLastname
# 並び順はアイマスCGWiki準拠になるように頑張る
# アルファベット表記は原則カードの表記準拠
# こちらは正規表現でマッチ「後」のハッシュテーブルなので、制御文字のエスケープは不要
exports.table = {

# 2ページ
  '櫻井桃華': 'SakuraiMomoka'
  '櫻井桃華+': 'SakuraiMomoka+'
  '江上椿': 'EgamiTsubaki'
  '江上椿+': 'EgamiTsubaki+'

# 3ページ
  '［バレンタイン］椎名法子': 'ValentineShinaNoriko'
  '［バレンタイン］椎名法子+': 'ValentineShinaNoriko+'
  '前川みく': 'MaekawaMiku'
  '前川みく+': 'MaekawaMiku+'
  '赤西瑛梨華': 'AkanishiErika'
  '赤西瑛梨華+': 'AkanishiErika+'
  '松原早耶': 'MatsubaraSaya'
  '松原早耶+': 'MatsubaraSaya+'


# 4ページ
  '相原雪乃': 'AiharaYukino'
  '相原雪乃+': 'AiharaYukino+'
  '宮本フレデリカ': 'MiyamotoFrederica'
  '宮本フレデリカ+': 'MiyamotoFrederica+'
  '小早川紗枝': 'KobayakawaSae'
  '小早川紗枝+': 'KobayakawaSae+'
  '西園寺琴歌': 'SaionjiKotoka'
  '西園寺琴歌+': 'SaionjiKotoka+'
  '双葉杏': 'FutabaAnzu'
  '双葉杏+': 'FutabaAnzu+'
  '楊菲菲': 'YaoFueiFuei'
  '楊菲菲+': 'YaoFueiFuei+'
  '桃井あずき': 'MomoiAzuki'
  '桃井あずき+': 'MomoiAzuki+'
  '涼宮星花': 'SuzumiyaSeika'
  '涼宮星花+': 'SuzumiyaSeika+'

# 5ページ
  '月宮雅': 'TsukimiyaMiyabi'
  '月宮雅+': 'TsukimiyaMiyabi+'
  '兵藤レナ': 'HyodoRena'
  '兵藤レナ+': 'HyodoRena+'
  '道明寺歌鈴': 'DomyojiKarin'
  '道明寺歌鈴+': 'DomyojiKarin+'
  '高槻やよい': 'TakatsukiYayoi'
  '高槻やよい+': 'TakatsukiYayoi+'
  '菊地真': 'KikuchiMakoto'
  '菊地真+': 'KikuchiMakoto+'
  '我那覇響': 'GanahaHibiki'
  '我那覇響+': 'GanahaHibiki+'
  '柳清良': 'YanagiKiyora'
  '柳清良+': 'YanagiKiyora+'
  '［聖夜］小日向美穂': 'SeiyaKohinataMiho'
  '［聖夜］小日向美穂+': 'SeiyaKohinataMiho+'

# 6
  '井村雪菜': 'ImuraSetsuna'
  '井村雪菜+': 'ImuraSetsuna+'
  '［新春］道明寺歌鈴': 'ShinshunDomyojiKarin'
  '［新春］道明寺歌鈴+': 'ShinshunDomyojiKarin+'
  '日下部若葉': 'KusakabeWakaba'
  '日下部若葉+': 'KusakabeWakaba+'
  '榊原里美': 'SakakibaraSatomi'
  '榊原里美+': 'SakakibaraSatomi+'
  '輿水幸子': 'KoshimizuSachiko'
  '輿水幸子+': 'KoshimizuSachiko+'
  '安斎都': 'AnzaiMiyako'
  '安斎都+': 'AnzaiMiyako+'
  '浅野風香': 'AsanoFuka'
  '浅野風香+': 'AsanoFuka+'
  '大西由里子': 'OnishiYuriko'
  '大西由里子+': 'OnishiYuriko+'

# 7
  '［バレンタイン］緒方智絵里': 'ValentineOgataChieri'
  '［バレンタイン］緒方智絵里+': 'ValentineOgataChieri+'
  '安部菜々': 'AbeNana'
  '安部菜々+': 'AbeNana+'
  '工藤忍': 'KudoShinobu'
  '工藤忍+': 'KudoShinobu+'
  '栗原ネネ': 'KuriharaNene'
  '栗原ネネ+': 'KuriharaNene+'
  '［ひな祭り］福山舞': 'HinamatsuriFukuyamaMai'
  '［ひな祭り］福山舞+': 'HinamatsuriFukuyamaMai'
  '［純粋奏者］水本ゆかり': 'JunsuisoshaMizumotoYukari'
  '［純粋奏者］水本ゆかり+': 'JunsuisoshaMizumotoYukari+'
  '古賀小春': 'KogaKoharu'
  '古賀小春+': 'KogaKoharu+'
  '［お花見］中野有香': 'OhanamiNakanoYuka'
  '［お花見］中野有香+': 'OhanamiNakanoYuka+'

# 8
  '［制服コレクション］楊菲菲': 'SeifukucollectionYaoFueiFuei'
  '［制服コレクション］楊菲菲+': 'SeifukucollectionYaoFueiFuei+'
  '［テーマパーク］柳瀬美由紀': 'ThemeparkYanaseMiyuki'
  '［テーマパーク］柳瀬美由紀+': 'ThemeparkYanaseMiyuki+'
  '［ウサコちゃんと］持田亜里沙': 'UsakochantoMochidaArisa'
  '［ウサコちゃんと］持田亜里沙+': 'UsakochantoMochidaArisa+'
  '［パジャマパーティー］緒方智絵里': 'PajamapartyOgataChieri'
  '［パジャマパーティー］緒方智絵里+': 'PajamapartyOgataChieri+'
  '［パジャマパーティー］間中美里': 'PajamapartyManakaMisato'
  '［パジャマパーティー］間中美里+': 'PajamapartyManakaMisato+'
  '［沖縄元気っ娘］我那覇響': 'OkinawagenkikkoGanahaHibiki'
  '［沖縄元気っ娘］我那覇響+': 'OkinawagenkikkoGanahaHibiki+'
  '［王子様な女子］菊地真': 'OjisamanajoshiKikuchiMakoto'
  '［王子様な女子］菊地真+': 'OjisamanajoshiKikuchiMakoto+'
  '［セクシーキャット］前川みく': 'SexycatMaekawaMiku'
  '［セクシーキャット］前川みく+': 'SexycatMaekawaMiku+'

# 9ページ
  '［秘めた輝き］原田美世': 'HimetakagayakiHaradaMiyo'
  '［秘めた輝き］原田美世+': 'HimetakagayakiHaradaMiyo+'
  '［天才ロボ少女］池袋晶葉': 'TensairoboshojoIkebukuroAkiha'
  '［天才ロボ少女］池袋晶葉+': 'TensairoboshojoIkebukuroAkiha+'
  '［艶娘大作戦］桃井あずき': 'YoendaisakusenMomoiAzuki'
  '［艶娘大作戦］桃井あずき+': 'YoendaisakusenMomoiAzuki'
  '［だらだら妖精］双葉杏': 'DaradarayoseiFutabaAnzu'
  '［だらだら妖精］双葉杏+': 'DaradarayoseiFutabaAnzu+'
  '［戦国姫］小日向美穂+': 'SengokuhimeKohinataMiho+'
  '［薔薇色お姫様］櫻井桃華': 'BarairoohimesamaSakuraiMomoka'
  '［薔薇色お姫様］櫻井桃華+': 'BarairoohimesamaSakuraiMomoka+'
  '［桜ガール］月宮雅': 'SakuragirlTsukimiyaMiyabi'
  '［桜ガール］月宮雅+': 'SakuragirlTsukimiyaMiyabi+'
  '［ふわふわスマイル］三村かな子': 'FuwafuwasmileMimuraKanako'
  'SRかな子': 'FuwafuwasmileMimuraKanako'
  '［ふわふわスマイル］三村かな子+': 'FuwafuwasmileMimuraKanako+'
  '［制服ベージュ］天海春香': 'SeifukubeigeAmamiHaruka'
  '［王道アイドル］天海春香': 'OudouidolAmamiHaruka'

# 10
  '［王道アイドル］天海春香+': 'OudouidolAmamiHaruka+'
  '［CDデビュー］三村かな子': 'CDdebutMimuraKanako'
  '［CDデビュー］三村かな子+': 'CDdebutMimuraKanako+'
  '［CDデビュー］双葉杏': 'CDdebutFutabaAnzu'
  '［CDデビュー］双葉杏+': 'CDdebutFutabaAnzu+'
  '招待春香': 'SeifukubeigeAmamiHaruka'
  '［普通の女の子］天海春香': 'FutsunoonnanokoAmamiHaruka'
  '［普通の女の子］天海春香+': 'FutsunoonnanokoAmamiHaruka'

# 11
  '［制服グリーン］高槻やよい': 'SeifukugreenTakatsukiYayoi'
  '招待やよい': 'SeifukugreenTakatsukiYayoi'
  '［元気120%］高槻やよい': 'Genki120percentTakatsukiYayoi'
  '［元気120%］高槻やよい+': 'Genki120percentTakatsukiYayoi+'

# other
  '［大器晩成］道明寺歌鈴': 'TaikibanseiDomyojiKarin'
  '［大器晩成］道明寺歌鈴+': 'TaikibanseiDomyojiKarin+'
  'クラリス': 'Clarice'
  'クラリス+': 'Clarice+'
  '［スポーツ祭］今井加奈': 'SportssaiImaiKana'
  '［スポーツ祭］今井加奈+': 'SportssaiImaiKana'
  '［ニュージェネレーション］島村卯月': 'NewgenerationShimamuraUzuki'
  '［ニュージェネレーション］島村卯月+': 'NewgenerationShimamuraUzuki+'


# クール
# 2
  '三船美優': 'MifuneMiyu'
  '三船美優+': 'MifuneMiyu+'
  '服部瞳子': 'HattoriToko'
  '服部瞳子+': 'HattoriToko+'

# 3ページ
  '［バレンタイン］佐々木千枝': 'ValentineSasakiChie'
  '［バレンタイン］佐々木千枝+': 'ValentineSasakiChie+'
  '［お花見］相川千夏': 'OhanamiAikawaChinatsu'
  '［お花見］相川千夏+': 'OhanamiAikawaChinatsu+'
  'ヘレン': 'Helen'
  'ヘレン+': 'Helen+'
  '松永涼': 'MatsunagaRyo'
  '松永涼+': 'MatsunagaRyo+'
  '小室千奈美': 'KomuroChinami'
  '小室千奈美+': 'KomuroChinami+'

# 4
  '高峯のあ': 'TakamineNoa'
  '高峯のあ+': 'TakamineNoa+'
  '高垣楓': 'TakagakiKaede'
  '高垣楓+': 'TakagakiKaede+'
  '神崎蘭子': 'KanzakiRanko'
  '神崎蘭子+': 'KanzakiRanko+'
  '伊集院惠': 'IjuinMegumi'
  '伊集院惠+': 'IjuinMegumi+'
  '柊志乃': 'HiragiShino'
  '柊志乃+': 'HiragiShino+'
  '北条加蓮': 'HojoKaren'
  '北条加蓮+': 'HojoKaren+'
  'ケイト': 'Kate'
  'ケイト+': 'Kate+'
  '瀬名詩織': 'SenaShiori'
  '瀬名詩織+': 'SenaShiori+'

# 5
  '綾瀬穂乃香': 'AyaseHonoka'
  '綾瀬穂乃香+': 'AyaseHonoka+'
  '佐城雪美': 'SajoYukimi'
  '佐城雪美+': 'SajoYukimi+'
  '如月千早': 'KisaragiChihaya'
  '如月千早+': 'KisaragiChihaya'
  '三浦あずさ': 'MiuraAzusa'
  '三浦あずさ+': 'MiuraAzusa+'
  '秋月律子': 'AkizukiRitsuko'
  '秋月律子+': 'AkizukiRitsuko+'
  '四条貴音': 'ShijoTakane'
  '四条貴音+': 'ShijoTakane+'
  '篠原礼': 'ShinoharaRei'
  '篠原礼+': 'ShinoharaRei+'
  '［聖夜］神谷奈緒': 'SeiyaKamiyaNao'
  '［聖夜］神谷奈緒+': 'SeiyaKamiyaNao+'

# 6
  '［新春］東郷あい': 'ShinshunTogoAi'
  '［新春］東郷あい+': 'ShinshunTogoAi+'
  '和久井留美': 'WakuiRumi'
  '和久井留美+': 'WakuiRumi+'
  '吉岡沙紀': 'YoshiokaSaki'
  '吉岡沙紀+': 'YoshiokaSaki+'
  '梅木音葉': 'UmekiOtoha'
  '梅木音葉+': 'UmekiOtoha+'
  '白坂小梅': 'ShirasakaKoume'
  '白坂小梅+': 'ShirasakaKoume+'
  '岸部彩華': 'KishibeAyaka'
  '岸部彩華+': 'KishibeAyaka+'
  '氏家むつみ': 'UjiieMutsumi'
  '氏家むつみ+': 'UjiieMutsumi+'
  '西川保奈美': 'NishikawaHonami'
  '西川保奈美+': 'NishikawaHonami+'

# 7
  '［バレンタイン］多田李衣菜': 'ValentineTadaRina'
  '［バレンタイン］多田李衣菜+': 'ValentineTadaRina+'
  '成宮由愛': 'NarumiyaYume'
  '成宮由愛+': 'NarumiyaYume+'
  '［ひな祭り］藤居朋': 'HinamatsuriFujiTomo'
  '［ひな祭り］藤居朋+': 'HinamatsuriFujiTomo+'
  '［眼鏡マジック］上条春菜': 'MeganemagicKamijoHaruna'
  '［眼鏡マジック］上条春菜+': 'MeganemagicKamijoHaruna+'
  '［お花見］水木聖來': 'OhanamiMizukiSeira'
  '［お花見］水木聖來+': 'OhanaiMizukiSeira+'
  '［制服コレクション］北条加蓮': 'SeifukucollectionHojoKaren'
  '［制服コレクション］北条加蓮+': 'SeifukucollectionHojoKaren'
  '［制服コレクション］多田李衣菜': 'SeifukucollectionTadaRina'
  '［制服コレクション］多田李衣菜+': 'SeifukucollectionTadaRina+'
  '塩見周子': 'ShiomiSyuko'
  '塩見周子+': 'ShiomiSyuko+'

# 8
  '脇山珠美': 'WakiyamaTamami'
  '脇山珠美+': 'WakiyamaTamami+'
  '［テーマパーク］松永涼': 'ThemeparkMatsunagaRyo'
  '［テーマパーク］松永涼+': 'ThemeparkMatsunagaRyo+'
  '［パジャマパーティー］黒川千秋': 'PajamapartyKurokawaChiaki'
  '［パジャマパーティー］黒川千秋+': 'PajamapartyKurokawaChiaki+'
  '［パジャマパーティー］川島瑞樹': 'PajamapartyKawashimaMizuki'
  '［パジャマパーティー］川島瑞樹+': 'PajamapartyKawashimaMizuki+'
  '岡崎泰葉': 'OkazakiYasuha'
  '岡崎泰葉+': 'OkazakiYasuha+'
  '［孤高の歌姫］如月千早': 'KokonoutahimeKisaragiChihaya'
  '［孤高の歌姫］如月千早+': 'KokonoutahimeKisaragiChihaya+'
  '［皆のお姉さん］三浦あずさ': 'MinnanoonesanMiuraAzusa'
  '［皆のお姉さん］三浦あずさ+': 'MinnanoonesanMiuraAzusa+'
  '［ニュージェネレーション］渋谷凛': 'NewgenerationShibuyaRin'
  '［ニュージェネレーション］渋谷凛+': 'NewgenerationShibuyaRin+'

# 9
  '［博識子女］古澤頼子': 'HakushikishijoFurusawaYoriko'
  '［博識子女］古澤頼子+': 'HakushikishijoFurusawaYoriko+'
  '［聖なる乙女］望月聖': 'SeinaruotomeMochizukiHijiri'
  '［聖なる乙女］望月聖+': 'SeinaruotomeMochizukiHijiri+'
  '［エステル衣装］三浦あずさ+': 'EstherishoMiuraAzusa+'
  '［幸運の女神］鷹富士茄子': 'KounnomegamiTakafujiNasuko'
  '［幸運の女神］鷹富士茄子+': 'KounnomegamiTakafujiNasuko+'
  '［銀色の王女］四条貴音': 'GinironoojoShijoTakane'
  '［銀色の王女］四条貴音+': 'GinironoojoShijoTakane+'
  '［ピュアハート］綾瀬穂乃香': 'PureheartAyaseHonoka'
  '［ピュアハート］綾瀬穂乃香+': 'PureheartAyaseHonoka+'
  '［天使な堕天使］神崎蘭子': 'TenshinadatenshiKanzakiRanko'
  '［天使な堕天使］神崎蘭子+': 'TenshinadatenshiKanzakiRanko+'
  '［寡黙の女王］高峯のあ': 'KamokunojooTakamineNoa'
  '［寡黙の女王］高峯のあ+': 'KamokunojooTakamineNoa+'
  '［ほろ酔い艶美］柊志乃': 'HoroyoiembiHiragiShino'

# 10
  '［ほろ酔い艶美］柊志乃+': 'HoroyoiembiHiragiShino+'
  '［神秘の女神］高垣楓': 'ShimpinomegamiTakagakiKaede'
  '［神秘の女神］高垣楓+': 'ShimpinomegamiTakagakiKaede+'
  '［CDデビュー］渋谷凛': 'CDdebutShibuyaRin'
  '［CDデビュー］渋谷凛+': 'CDdebutShibuyaRin+'
  '［CDデビュー］高垣楓': 'CDdebutTakagakiKaede'
  '［CDデビュー］高垣楓+': 'CDdebutTakagakiKaede+'
  '［魔法のスマイル］佐々木千枝': 'MahonosmileSasakiChie'
  '［魔法のスマイル］佐々木千枝+': 'MahonosmileSasakiChie+'
  '［スクーリッシュガール］如月千早+': 'SchoolishgirlKisaragiChihaya+'
  '［恥じらい乙女］神谷奈緒': 'HajiraiotomeKamiyaNao'
  '［恥じらい乙女］神谷奈緒+': 'HajiraiotomeKamiyaNao+'
  '［制服ブルー］如月千早': 'SeifukublueKisaragiChihaya'
  '招待千早': 'SeifukublueKisaragiChihaya'

# 11
  '［瑠璃の歌姫］如月千早': 'RurinoutahimeKisaragiChihaya'
  '［瑠璃の歌姫］如月千早+': 'RurinoutahimeKisaragiChihaya+'
  '［神秘の女神］高垣楓': 'ShimpinomegamiTakagakiKaede'
  '［神秘の女神］高垣楓+': 'ShimpinomegamiTakagakiKaede+'

# other
  '［オフスタイルネイビー］和久井留美': 'OffstylenavyWakuiRumi'
  '［オフスタイルネイビー］和久井留美+': 'OffstylenavyWakuiRumi+'
  '［麗しの花嫁］和久井留美': 'UruwashinohanayomeWakuiRumi'
  '［麗しの花嫁］和久井留美+': 'UruwashinohanayomeWakuiRumi+'
  '［スポーツ祭］桐野アヤ': 'SportssaiKirinoAya'
  '［スポーツ祭］桐野アヤ+': 'SportssaiKirinoAya+'
  '［スポーツ祭］小室千奈美': 'SportssaiKomuroChinami'
  '［スポーツ祭］小室千奈美+': 'SportssaiKomuroChinami+'

# パッション
# 2
  '喜多見柚': 'KitamiYuzu'
  '喜多見柚+': 'KitamiYuzu+'
  '上田鈴帆': 'UedaSuzuho'
  '上田鈴帆+': 'UedaSuzuho+'

# 3ページ
  '［バレンタイン］高森藍子': 'ValentineTakamoriAiko'
  '［バレンタイン］高森藍子+': 'ValentineTakamoriAiko+'
  '［お花見］大槻唯': 'OhanamiOtsukiYui'
  '［お花見］大槻唯+': 'OhanamiOtsukiYui+'
  '相葉夕美': 'AibaYumi'
  '相葉夕美+': 'AibaYumi+'
  '野々村そら': 'NonomuraSora'
  '野々村そら+': 'NonomuraSora+'

# 4
  '浜川愛結奈': 'HamakawaAyuna'
  '浜川愛結奈+': 'HamakawaAyuna+'
  '若林智香': 'WakabayashiTomoka'
  '若林智香+': 'WakabayashiTomoka+'
  '城ヶ崎美嘉': 'JougasakiMika'
  '城ヶ崎美嘉+': 'JougasakiMika+'
  '城ヶ崎莉嘉': 'JougasakiRika'
  '城ヶ崎莉嘉+': 'JougasakiRika+'
  '仙崎恵磨': 'SenzakiEma'
  '仙崎恵磨+': 'SenzakiEma+'
  '日野茜': 'HinoAkane'
  '日野茜+': 'HinoAkane+'
  '諸星きらり': 'MoroboshiKirari'
  '諸星きらり+': 'MoroboshiKirari+'
  '十時愛梨': 'TotokiAiri'
  '十時愛梨+': 'TotokiAiri+'

# 5
  'ナターリア': 'Natalia'
  'ナターリア+': 'Natalia+'
  '相馬夏美': 'SomaNatsumi'
  '相馬夏美+': 'SomaNatsumi+'
  '槙原志保': 'MakiharaShiho'
  '槙原志保+': 'MakiharaShiho+'
  '萩原雪歩': 'HagiwaraYukiho'
  '萩原雪歩+': 'HagiwaraYukiho+'
  '双海亜美': 'FutamiAmi'
  '双海亜美+': 'FutamiAmi+'
  '双海真美': 'FutamiMami'
  '双海真美+': 'FutamiMami+'
  '星井美希': 'HoshiiMiki'
  '星井美希+': 'HoshiiMiki+'
  '向井拓海': 'MukaiTakumi'
  '向井拓海+': 'MukaiTakumi+'

# 6
  '水瀬伊織': 'MinaseIori'
  '水瀬伊織+': 'MinaseIori+'
  '［聖夜］ナターリア': 'SeiyaNatalia'
  '［聖夜］ナターリア+': 'SeiyaNatalia+'
  '［新春］龍崎薫': 'ShinshunRyuzakiKaoru'
  '［新春］龍崎薫+': 'ShinshunRyuzakiKaoru'
  '市原仁奈': 'IchiharaNina'
  '市原仁奈+': 'IchiharaNina'
  '杉坂海': 'SugisakaUmi'
  '杉坂海+': 'SugisakaUmi+'
  '喜多日菜子': 'KitaHinako'
  '喜多日菜子+': 'KitaHinako+'
  '北川真尋': 'KitagawaMahiro'
  '北川真尋+': 'KitagawaMahiro+'
  'メアリー･コクラン': 'MaryCochran'
  'メアリー･コクラン+': 'MaryCochran+'

# 7
  '小松伊吹': 'KomatsuIbuki'
  '小松伊吹+': 'KomatsuIbuki+'
  '［バレンタイン］赤城みりあ': 'ValentineAkagiMiria'
  '［バレンタイン］赤城みりあ+': 'ValentineAkagiMiria+'
  '三好紗南': 'MiyoshiSana'
  '三好紗南+': 'MiyoshiSana+'
  'キャシー･グラハム': 'CathyGraham'
  'キャシー･グラハム+': 'CathyGraham+'
  '［ひな祭り］上田鈴帆': 'HinamatsuriUedaSuzuho'
  '［ひな祭り］上田鈴帆+': 'HinamatsuriUedaSuzuho+'
  '難波笑美': 'NambaEmi'
  '難波笑美+': 'NambaEmi'
  '［お花見］姫川友紀': 'OhanamiHimekawaYuki'
  '［お花見］姫川友紀+': 'OhanamiHimekawaYuki+'
  '［制服コレクション］木村夏樹': 'SeifukucollectionKimuraNatsuki'
  '［制服コレクション］木村夏樹+': 'SeifukucollectionKimuraNatsuki+'

# 8
  '［制服コレクション］矢口美羽': 'SeifukucollectionYaguchiMiu'
  '［制服コレクション］矢口美羽+': 'SeifukucollectionYaguchiMiu+'
  '浜口あやめ': 'HamaguchiAyame'
  '浜口あやめ+': 'HamaguchiAyame+'
  '［フラワーブーケ］相葉夕美': 'FlowerbouquetAibaYumi'
  '［フラワーブーケ］相葉夕美+': 'FlowerbouquetAibaYumi+'
  '［テーマパーク］斉藤洋子': 'ThemeparkSaitoYoko'
  '［テーマパーク］斉藤洋子+': 'ThemeparkSaitoYoko+'
  '［パジャマパーティー］若林智香': 'PajamapartyWakabayashiTomoka'
  '［パジャマパーティー］若林智香+': 'PajamapartyWakabayashiTomoka+'
  '［高飛車お嬢様］水瀬伊織': 'TakabishaojosamaMinaseIori'
  '［高飛車お嬢様］水瀬伊織+': 'TakabishaojosamaMinaseIori+'
  '［臆病な天使］萩原雪歩': 'OkubyonatenshiHagiwaraYukiho'
  '［臆病な天使］萩原雪歩+': 'OkubyonatenshiHagiwaraYukiho+'
  '［小さな英雄］南条光': 'ChiisanaeiyuNanjoHikaru'
  '［小さな英雄］南条光+': 'ChiisanaeiyuNanjoHikaru+'

# 9
  '［聖夜の使者］イヴ・サンタクロース': 'SeiyanoshishaEveSantaclaus'
  '［聖夜の使者］イヴ・サンタクロース+': 'SeiyanoshishaEveSantaclaus+'
  '［ラブリープリンセス］諸星きらり': 'LovelyprincessMoroboshiKirari'
  '［ラブリープリンセス］諸星きらり+': 'LovelyprincessMoroboshiKirari+'
  '［スイートバレンタイン］十時愛梨': 'SweetvalentineTotokiAiri'
  '［スイートバレンタイン］十時愛梨+': 'SweetvalentineTotokiAiri+'
  '［パワフル双子妹］双海亜美': 'PowerfulfutagoimotoFutamiAmi'
  '［パワフル双子妹］双海亜美+': 'PowerfulfutagoimotoFutamiAmi+'
  '［パワフル双子姉］双海真美': 'PowerfulfutagoaneFutamiMami'
  '［パワフル双子姉］双海真美+': 'PowerfulfutagoaneFutamiMami+'
  '［お転婆ひな娘］喜多見柚': 'OtembahinamusumeKitamiYuzu'
  '［お転婆ひな娘］喜多見柚+': 'OtembahinamusumeKitamiYuzu+'
  '［CDデビュー］城ヶ崎莉嘉': 'CDdebutJougasakiRika'
  '［CDデビュー］城ヶ崎莉嘉+': 'CDdebutJougasakiRika+'
  '［妄想お姫様］喜多日菜子': 'MousouohimesamaKitaHinako'
  '［妄想お姫様］喜多日菜子+': 'MousouohimesamaKitaHinako+'

# 10
  '［眠れる姫君］星井美希': 'NemureruhimegimiHoshiiMiki'
  '［眠れる姫君］星井美希+': 'NemureruhimegimiHoshiiMiki+'
  '［制服オレンジ］星井美希': 'SeifukuorangeHoshiiMiki'
  '招待美希': 'SeifukuorangeHoshiiMiki'
  '［才能無限大］星井美希': 'SainomugendaiHoshiiMiki'
  '［才能無限大］星井美希+': 'SainomugendaiHoshiiMiki'
  '［制服ブルー］萩原雪歩': 'SeifukublueHagiwaraYukiho'
  '招待雪歩': 'SeifukublueHagiwaraYukiho'

# 11
  '［癒しの天使］萩原雪歩': 'IyashinotenshiHagiwaraYukiho'
  '［癒しの天使］萩原雪歩+': 'IyashinotenshiHagiwaraYukiho+'
  'ベテラントレーナー': 'VeteranTrainer'
  'マスタートレーナー': 'MasterTrainer'
  '［聖夜］トレーナー': 'SeiyaTrainer'
  '［聖夜］ベテラントレーナー': 'SeiyaVeteranTrainer'
  '［新春］トレーナー': 'ShinshunTrainer'
  '［新春］ベテラントレーナー': 'ShinshunVeteranTrainer'
  '［バレンタイン］トレーナー': 'ValentineTrainer'

# 12
  '［バレンタイン］ベテラントレーナー': 'ValentineVeteranTrainer'

# other
  '［ふんわりガール］高森藍子': 'FunwarigirlTakamoriAiko'
  '［ふんわりガール］高森藍子+': 'FunwarigirlTakamoriAiko+'
  '［姉御肌］向井拓海': 'AnegohadaMukaiTakumi'
  '［姉御肌］向井拓海+': 'AnegohadaMukaiTakumi+'
  '［スポーツ祭］沢田麻里菜': 'SportssaiSawadaMarina'
  '［スポーツ祭］沢田麻里菜+': 'SportssaiSawadaMarina+'
  '［スポーツ祭］北川真尋': 'SportssaiKitagawaMahiro'
  '［スポーツ祭］北川真尋+': 'SportssaiKitagawaMahiro+'
  '［ハッピーブライダル］ナターリア': 'HappybridalNatalia'

}


# アイドル一覧
# 正規表現に突っ込んで検索するので制御文字はエスケープすること
# ただし+,[,]だけは全部処理側でエスケープする仕様に変更したよ
# aliasも全部書くべしし
exports.list = [
# 2
  '櫻井桃華'
  '櫻井桃華+'
  '江上椿'
  '江上椿+'

# 3
  '［バレンタイン］椎名法子'
  '［バレンタイン］椎名法子+'
  '前川みく'
  '前川みく+'
  '赤西瑛梨華'
  '赤西瑛梨華+'
  '松原早耶'
  '松原早耶+'

# 4
  '相原雪乃'
  '相原雪乃+'
  '宮本フレデリカ'
  '宮本フレデリカ+'
  '小早川紗枝'
  '小早川紗枝+'
  '西園寺琴歌'
  '西園寺琴歌+'
  '双葉杏'
  '双葉杏+'
  '楊菲菲'
  '楊菲菲+'
  '桃井あずき'
  '桃井あずき+'
  '涼宮星花'
  '涼宮星花+'

# 5
  '月宮雅'
  '月宮雅+'
  '兵藤レナ'
  '兵藤レナ+'
  '道明寺歌鈴'
  '道明寺歌鈴+'
  '高槻やよい'
  '高槻やよい+'
  '菊地真'
  '菊地真+'
  '我那覇響'
  '我那覇響+'
  '柳清良'
  '柳清良+'
  '［聖夜］小日向美穂'
  '［聖夜］小日向美穂+'

# 6
  '井村雪菜'
  '井村雪菜+'
  '［新春］道明寺歌鈴'
  '［新春］道明寺歌鈴+'
  '日下部若葉'
  '日下部若葉+'
  '榊原里美'
  '榊原里美+'
  '輿水幸子'
  '輿水幸子+'
  '安斎都'
  '安斎都+'
  '浅野風香'
  '浅野風香+'
  '大西由里子'
  '大西由里子+'

# 7
  '［バレンタイン］緒方智絵里'
  '［バレンタイン］緒方智絵里+'
  '安部菜々'
  '安部菜々+'
  '工藤忍'
  '工藤忍+'
  '栗原ネネ'
  '栗原ネネ+'
  '［ひな祭り］福山舞'
  '［ひな祭り］福山舞+'
  '［純粋奏者］水本ゆかり'
  '［純粋奏者］水本ゆかり+'
  '古賀小春'
  '古賀小春+'
  '［お花見］中野有香'
  '［お花見］中野有香+'

# 8
  '［制服コレクション］楊菲菲'
  '［制服コレクション］楊菲菲+'
  '［テーマパーク］柳瀬美由紀'
  '［テーマパーク］柳瀬美由紀+'
  '［ウサコちゃんと］持田亜里沙'
  '［ウサコちゃんと］持田亜里沙+'
  '［パジャマパーティー］緒方智絵里'
  '［パジャマパーティー］緒方智絵里+'
  '［パジャマパーティー］間中美里'
  '［パジャマパーティー］間中美里+'
  '［沖縄元気っ娘］我那覇響'
  '［沖縄元気っ娘］我那覇響+'
  '［王子様な女子］菊地真'
  '［王子様な女子］菊地真+'
  '［セクシーキャット］前川みく'
  '［セクシーキャット］前川みく+'

# 9
  '［秘めた輝き］原田美世'
  '［秘めた輝き］原田美世+'
  '［天才ロボ少女］池袋晶葉'
  '［艶娘大作戦］桃井あずき'
  '［艶娘大作戦］桃井あずき+'
  '［だらだら妖精］双葉杏'
  '［だらだら妖精］双葉杏+'
  '［戦国姫］小日向美穂+'
  '［薔薇色お姫様］櫻井桃華'
  '［薔薇色お姫様］櫻井桃華+'
  '［桜ガール］月宮雅'
  '［桜ガール］月宮雅+'
  '［ふわふわスマイル］三村かな子'
  'SRかな子'
  '［ふわふわスマイル］三村かな子+'
  '［王道アイドル］天海春香'

#10
  '［王道アイドル］天海春香+'
  '［CDデビュー］三村かな子'
  '［CDデビュー］三村かな子+'
  '［CDデビュー］双葉杏'
  '［CDデビュー］双葉杏+'
  '［制服ベージュ］天海春香'
  '招待春香'
  '［普通の女の子］天海春香'
  '［普通の女の子］天海春香+'

# 11
  '［制服グリーン］高槻やよい'
  '招待やよい'
#  '［元気120%］高槻やよい'
#  '［元気120%］高槻やよい+'

# other
  'クラリス'
  'クラリス+'
  '［大器晩成］道明寺歌鈴'
  '［大器晩成］道明寺歌鈴+'
  '［ニュージェネレーション］島村卯月'
  '［スポーツ祭］今井加奈'


# クール
# 2
  '三船美優'
  '三船美優+'
  '服部瞳子'
  '服部瞳子+'

# 3ページ
  '［バレンタイン］佐々木千枝'
  '［バレンタイン］佐々木千枝+'
  '［お花見］相川千夏'
  '［お花見］相川千夏+'
  'ヘレン'
  'ヘレン+'
  '松永涼'
  '松永涼+'
  '小室千奈美'
  '小室千奈美+'

# 4
  '高峯のあ'
  '高峯のあ+'
  '高垣楓'
  '高垣楓+'
  '神崎蘭子'
  '神崎蘭子+'
  '伊集院惠'
  '伊集院惠+'
  '柊志乃'
  '柊志乃+'
  '北条加蓮'
  '北条加蓮+'
  'ケイト'
  'ケイト+'
  '瀬名詩織'
  '瀬名詩織+'

# 5
  '綾瀬穂乃香'
  '綾瀬穂乃香+'
  '佐城雪美'
  '佐城雪美+'
  '如月千早'
  '如月千早+'
  '三浦あずさ'
  '三浦あずさ+'
  '秋月律子'
  '秋月律子+'
  '四条貴音'
  '四条貴音+'
  '篠原礼'
  '篠原礼+'
  '［聖夜］神谷奈緒'
  '［聖夜］神谷奈緒+'

# 6
  '［新春］東郷あい'
  '［新春］東郷あい+'
  '和久井留美'
  '和久井留美+'
  '吉岡沙紀'
  '吉岡沙紀+'
  '梅木音葉'
  '梅木音葉+'
  '白坂小梅'
  '白坂小梅+'
  '岸部彩華'
  '岸部彩華+'
  '氏家むつみ'
  '氏家むつみ+'
  '西川保奈美'
  '西川保奈美+'

# 7
  '［バレンタイン］多田李衣菜'
  '［バレンタイン］多田李衣菜+'
  '成宮由愛'
  '成宮由愛+'
  '［ひな祭り］藤居朋'
  '［ひな祭り］藤居朋+'
  '［眼鏡マジック］上条春菜'
  '［眼鏡マジック］上条春菜+'
  '［制服コレクション］北条加蓮'
  '［制服コレクション］北条加蓮+'
  '［制服コレクション］多田李衣菜'
  '［制服コレクション］多田李衣菜+'
  '塩見周子'
  '塩見周子+'

# 8
  '脇山珠美'
  '脇山珠美+'
  '［テーマパーク］松永涼'
  '［テーマパーク］松永涼+'
  '［パジャマパーティー］黒川千秋'
  '［パジャマパーティー］黒川千秋+'
  '［パジャマパーティー］川島瑞樹'
  '［パジャマパーティー］川島瑞樹+'
  '岡崎泰葉'
  '岡崎泰葉+'
  '［孤高の歌姫］如月千早'
  '［孤高の歌姫］如月千早+'
  '［皆のお姉さん］三浦あずさ'
  '［皆のお姉さん］三浦あずさ+'
  '［ニュージェネレーション］渋谷凛'
  '［ニュージェネレーション］渋谷凛+'

# 9
  '［博識子女］古澤頼子'
  '［博識子女］古澤頼子+'
  '［聖なる乙女］望月聖'
  '［聖なる乙女］望月聖+'
  '［エステル衣装］三浦あずさ+'
  '［幸運の女神］鷹富士茄子'
  '［幸運の女神］鷹富士茄子+'
  '［銀色の王女］四条貴音'
  '［銀色の王女］四条貴音+'
  '［ピュアハート］綾瀬穂乃香'
  '［ピュアハート］綾瀬穂乃香+'
  '［天使な堕天使］神崎蘭子'
  '［天使な堕天使］神崎蘭子+'
  '［寡黙の女王］高峯のあ'
  '［寡黙の女王］高峯のあ+'
  '［ほろ酔い艶美］柊志乃'

# 10
  '［ほろ酔い艶美］柊志乃+'
  '［神秘の女神］高垣楓'
  '［神秘の女神］高垣楓+'
  '［CDデビュー］渋谷凛'
  '［CDデビュー］渋谷凛+'
  '［CDデビュー］高垣楓'
  '［CDデビュー］高垣楓+'
  '［魔法のスマイル］佐々木千枝'
  '［魔法のスマイル］佐々木千枝+'
  '［スクーリッシュガール］如月千早+'
  '［恥じらい乙女］神谷奈緒'
  '［恥じらい乙女］神谷奈緒+'
  '［制服ブルー］如月千早'
  '招待千早'

# 11
  '［瑠璃の歌姫］如月千早'
  '［瑠璃の歌姫］如月千早+'

# other
  '［オフスタイルネイビー］和久井留美'
  '［麗しの花嫁］和久井留美'
  '［麗しの花嫁］和久井留美+'
  '［スポーツ祭］桐野アヤ'
  '［スポーツ祭］小室千奈美'

# パッション
# 2
  '喜多見柚'
  '喜多見柚+'
  '上田鈴帆'
  '上田鈴帆+'

# 3ページ
  '［バレンタイン］高森藍子'
  '［バレンタイン］高森藍子+'
  '［お花見］大槻唯'
  '［お花見］大槻唯+'
  '相葉夕美'
  '相葉夕美+'
  '野々村そら'
  '野々村そら+'

# 4
  '浜川愛結奈'
  '浜川愛結奈+'
  '若林智香'
  '若林智香+'
  '城ヶ崎美嘉'
  '城ヶ崎美嘉+'
  '城ヶ崎莉嘉'
  '城ヶ崎莉嘉+'
  '仙崎恵磨'
  '仙崎恵磨+'
  '日野茜'
  '日野茜+'
  '諸星きらり'
  '諸星きらり+'
  '十時愛梨'
  '十時愛梨+'

# 5
  'ナターリア'
  'ナターリア+'
  '相馬夏美'
  '相馬夏美+'
  '槙原志保'
  '槙原志保+'
  '萩原雪歩'
  '萩原雪歩+'
  '双海亜美'
  '双海亜美+'
  '双海真美'
  '双海真美+'
  '星井美希'
  '星井美希+'
  '向井拓海'
  '向井拓海+'

# 6
  '水瀬伊織'
  '水瀬伊織+'
  '［聖夜］ナターリア'
  '［聖夜］ナターリア+'
  '［新春］龍崎薫'
  '［新春］龍崎薫+'
  '市原仁奈'
  '市原仁奈+'
  '杉坂海'
  '杉坂海+'
  '喜多日菜子'
  '喜多日菜子+'
  '北川真尋'
  '北川真尋+'
  'メアリー･コクラン'
  'メアリー･コクラン+'

# 7
  '小松伊吹'
  '小松伊吹+'
  '［バレンタイン］赤城みりあ'
  '［バレンタイン］赤城みりあ+'
  '三好紗南'
  '三好紗南+'
  'キャシー･グラハム'
  'キャシー･グラハム+'
  '［ひな祭り］上田鈴帆'
  '［ひな祭り］上田鈴帆+'
  '難波笑美'
  '難波笑美+'
  '［お花見］姫川友紀'
  '［お花見］姫川友紀+'
  '［制服コレクション］木村夏樹'
  '［制服コレクション］木村夏樹+'

# 8
  '［制服コレクション］矢口美羽'
  '［制服コレクション］矢口美羽+'
  '浜口あやめ'
  '浜口あやめ+'
  '［フラワーブーケ］相葉夕美'
  '［フラワーブーケ］相葉夕美+'
  '［テーマパーク］斉藤洋子'
  '［テーマパーク］斉藤洋子+'
  '［パジャマパーティー］若林智香'
  '［パジャマパーティー］若林智香+'
  '［高飛車お嬢様］水瀬伊織'
  '［高飛車お嬢様］水瀬伊織+'
  '［臆病な天使］萩原雪歩'
  '［臆病な天使］萩原雪歩+'
  '［小さな英雄］南条光'
  '［小さな英雄］南条光+'

# 9
  '［聖夜の使者］イヴ・サンタクロース'
  '［聖夜の使者］イヴ・サンタクロース+'
  '［ラブリープリンセス］諸星きらり'
  '［ラブリープリンセス］諸星きらり+'
  '［スイートバレンタイン］十時愛梨'
  '［スイートバレンタイン］十時愛梨+'
  '［パワフル双子妹］双海亜美'
  '［パワフル双子妹］双海亜美+'
  '［パワフル双子姉］双海真美'
  '［パワフル双子姉］双海真美+'
  '［お転婆ひな娘］喜多見柚'
  '［お転婆ひな娘］喜多見柚+'
  '［CDデビュー］城ヶ崎莉嘉'
  '［CDデビュー］城ヶ崎莉嘉+'
  '［妄想お姫様］喜多日菜子'
  '［妄想お姫様］喜多日菜子+'


# 10
  '［眠れる姫君］星井美希'
  '［眠れる姫君］星井美希+'
  '［制服オレンジ］星井美希'
  '招待美希'
  '［才能無限大］星井美希'
  '［才能無限大］星井美希+'
  '［制服ブルー］萩原雪歩'
  '招待雪歩'

# 11
  '［癒しの天使］萩原雪歩'
  '［癒しの天使］萩原雪歩+'
  'ベテラントレーナー'
  'マスタートレーナー'
  '［聖夜］トレーナー'
  '［聖夜］ベテラントレーナー'
  '［新春］トレーナー'
  '［新春］ベテラントレーナー'
  '［バレンタイン］トレーナー'

# 12
  '［バレンタイン］ベテラントレーナー'

# other
  '［ふんわりガール］高森藍子'
  '［ふんわりガール］高森藍子+'
  '［姉御肌］向井拓海'
  '［姉御肌］向井拓海+'
  '［スポーツ祭］沢田麻里菜'
  '［スポーツ祭］北川真尋'
  '［ハッピーブライダル］ナターリア'
]



# id一覧
exports.ids = [
# 2
  'SakuraiMomoka'
  'SakuraiMomoka+'
  'EgamiTsubaki'
  'EgamiTsubaki+'

# 3ページ目
  'ValentineShinaNoriko'
  'ValentineShinaNoriko+'
  'MaekawaMiku'
  'MaekawaMiku+'
  'AkanishiErika'
  'AkanishiErika+'
  'MatsubaraSaya'
  'MatsubaraSaya+'

# 4
  'AiharaYukino'
  'AiharaYukino+'
  'MiyamotoFrederica'
  'MiyamotoFrederica+'
  'KobayakawaSae'
  'KobayakawaSae+'
  'SaionjiKotoka'
  'SaionjiKotoka+'
  'FutabaAnzu'
  'FutabaAnzu+'
  'YaoFueiFuei'
  'YaoFueiFuei+'
  'MomoiAzuki'
  'MomoiAzuki+'
  'SuzumiyaSeika'
  'SuzumiyaSeika+'

# 5
  'TsukimiyaMiyabi'
  'TsukimiyaMiyabi+'
  'HyodoRena'
  'HyodoRena+'
  'DomyojiKarin'
  'DomyojiKarin+'
  'TakatsukiYayoi'
  'TakatsukiYayoi+'
  'KikuchiMakoto'
  'KikuchiMakoto+'
  'GanahaHibiki'
  'GanahaHibiki+'
  'YanagiKiyora'
  'YanagiKiyora+'
  'SeiyaKohinataMiho'
  'SeiyaKohinataMiho+'

# 6
  'ImuraSetsuna'
  'ImuraSetsuna+'
  'ShinshunDomyojiKarin'
  'ShinshunDomyojiKarin+'
  'KusakabeWakaba'
  'KusakabeWakaba+'
  'SakakibaraSatomi'
  'SakakibaraSatomi+'
  'KoshimizuSachiko'
  'KoshimizuSachiko+'
  'AnzaiMiyako'
  'AnzaiMiyako+'
  'AsanoFuka'
  'AsanoFuka+'
  'OnishiYuriko'
  'OnishiYuriko+'

# 7
  'ValentineOgataChieri'
  'ValentineOgataChieri+'
  'AbeNana'
  'AbeNana+'
  'KudoShinobu'
  'KudoShinobu+'
  'KuriharaNene'
  'KuriharaNene+'
  'HinamatsuriFukuyamaMai'
  'HinamatsuriFukuyamaMai+'
  'JunsuisoshaMizumotoYukari'
  'JunsuisoshaMizumotoYukari+'
  'KogaKoharu'
  'KogaKoharu+'
  'OhanamiNakanoYuka'
  'OhanamiNakanoYuka+'

# 8
  'SeifukucollectionYaoFueiFuei'
  'SeifukucollectionYaoFueiFuei+'
  'ThemeparkYanaseMiyuki'
  'ThemeparkYanaseMiyuki+'
  'UsakochantoMochidaArisa'
  'UsakochantoMochidaArisa+'
  'PajamapartyOgataChieri'
  'PajamapartyOgataChieri+'
  'PajamapartyManakaMisato'
  'PajamapartyManakaMisato+'
  'OkinawagenkikkoGanahaHibiki'
  'OkinawagenkikkoGanahaHibiki+'
  'OjisamanajoshiKikuchiMakoto'
  'OjisamanajoshiKikuchiMakoto+'
  'SexycatMaekawaMiku'
  'SexycatMaekawaMiku+'

# 9ページ
  'HimetakagayakiHaradaMiyo'
  'HimetakagayakiHaradaMiyo+'
  'TensairoboshojoIkebukuroAkiha'
  'TensairoboshojoIkebukuroAkiha+'
  'YoendaisakusenMomoiAzuki'
  'YoendaisakusenMomoiAzuki+'
  'DaradarayoseiFutabaAnzu'
  'DaradarayoseiFutabaAnzu+'
  'SengokuhimeKohinataMiho+'
  'BarairoohimesamaSakuraiMomoka'
  'BarairoohimesamaSakuraiMomoka+'
  'SakuragirlTsukimiyaMiyabi'
  'SakuragirlTsukimiyaMiyabi+'
  'FuwafuwasmileMimuraKanako'
  'FuwafuwasmileMimuraKanako+'
  'OudouidolAmamiHaruka'

# 10
  'OudouidolAmamiHaruka+'
  'CDdebutMimuraKanako'
  'CDdebutMimuraKanako+'
  'CDdebutFutabaAnzu'
  'CDdebutFutabaAnzu+'
  'SeifukubeigeAmamiHaruka'
  'FutsunoonnanokoAmamiHaruka'
  'FutsunoonnanokoAmamiHaruka+'

# 11
  'SeifukugreenTakatsukiYayoi'
  'Genki120percentTakatsukiYayoi'
  'Genki120percentTakatsukiYayoi+'

# other
  'Clarice'
  'Clarice+'
  'TaikibanseiDomyojiKarin'
  'TaikibanseiDomyojiKarin+'
  'NewgenerationShimamuraUzuki'
  'SportssaiImaiKana'


# クール
# 2
  'MifuneMiyu'
  'MifuneMiyu+'
  'HattoriToko'
  'HattoriToko+'

# 3ページ
  'ValentineSasakiChie'
  'ValentineSasakiChie+'
  'OhanamiAikawaChinatsu'
  'OhanamiAikawaChinatsu+'
  'Helen'
  'Helen+'
  'MatsunagaRyo'
  'MatsunagaRyo+'
  'KomuroChinami'
  'KomuroChinami+'

# 4
  'TakamineNoa'
  'TakamineNoa+'
  'TakagakiKaede'
  'TakagakiKaede+'
  'KanzakiRanko'
  'KanzakiRanko+'
  'IjuinMegumi'
  'IjuinMegumi+'
  'HiragiShino'
  'HiragiShino+'
  'HojoKaren'
  'HojoKaren+'
  'Kate'
  'Kate+'
  'SenaShiori'
  'SenaShiori+'

# 5
  'AyaseHonoka'
  'AyaseHonoka+'
  'SajoYukimi'
  'SajoYukimi+'
  'KisaragiChihaya'
  'KisaragiChihaya+'
  'MiuraAzusa'
  'MiuraAzusa+'
  'AkizukiRitsuko'
  'AkizukiRitsuko+'
  'ShijoTakane'
  'ShijoTakane+'
  'ShinoharaRei'
  'ShinoharaRei+'
  'SeiyaKamiyaNao'
  'SeiyaKamiyaNao+'

# 6
  'ShinshunTogoAi'
  'ShinshunTogoAi+'
  'WakuiRumi'
  'WakuiRumi+'
  'YoshiokaSaki'
  'YoshiokaSaki+'
  'UmekiOtoha'
  'UmekiOtoha+'
  'ShirasakaKoume'
  'ShirasakaKoume+'
  'KishibeAyaka'
  'KishibeAyaka+'
  'UjiieMutsumi'
  'UjiieMutsumi+'
  'NishikawaHonami'
  'NishikawaHonami+'

# 7
  'ValentineTadaRina'
  'ValentineTadaRina+'
  'NarumiyaYume'
  'NarumiyaYume+'
  'HinamatsuriFujiTomo'
  'HinamatsuriFujiTomo+'
  'MeganemagicKamijoHaruna'
  'MeganemagicKamijoHaruna+'
  'SeifukucollectionHojoKaren'
  'SeifukucollectionHojoKaren+'
  'SeifukucollectionTadaRina'
  'SeifukucollectionTadaRina+'
  'ShiomiSyuko'
  'ShiomiSyuko+'

# 8
  'WakiyamaTamami'
  'WakiyamaTamami+'
  'ThemeparkMatsunagaRyo'
  'ThemeparkMatsunagaRyo+'
  'PajamapartyKurokawaChiaki'
  'PajamapartyKurokawaChiaki+'
  'PajamapartyKawashimaMizuki'
  'PajamapartyKawashimaMizuki+'
  'OkazakiYasuha'
  'OkazakiYasuha+'
  'KokonoutahimeKisaragiChihaya'
  'KokonoutahimeKisaragiChihaya+'
  'MinnanoonesanMiuraAzusa'
  'MinnanoonesanMiuraAzusa+'
  'NewgenerationShibuyaRin'
  'NewgenerationShibuyaRin+'

# 9
  'HakushikishijoFurusawaYoriko'
  'HakushikishijoFurusawaYoriko+'
  'SeinaruotomeMochizukiHijiri'
  'SeinaruotomeMochizukiHijiri+'
  'EstherishoMiuraAzusa+'
  'KounnomegamiTakafujiNasuko'
  'KounnomegamiTakafujiNasuko+'
  'GinironoojoShijoTakane'
  'GinironoojoShijoTakane+'
  'PureheartAyaseHonoka'
  'PureheartAyaseHonoka+'
  'TenshinadatenshiKanzakiRanko'
  'TenshinadatenshiKanzakiRanko+'
  'KamokunojooTakamineNoa'
  'KamokunojooTakamineNoa+'
  'HoroyoiembiHiragiShino'

# 10
  'HoroyoiembiHiragiShino+'
  'SeifukublueKisaragiChihaya'
  'ShimpinomegamiTakagakiKaede'
  'ShimpinomegamiTakagakiKaede+'
  'CDdebutShibuyaRin'
  'CDdebutShibuyaRin+'
  'CDdebutTakagakiKaede'
  'CDdebutTakagakiKaede+'
  'MahonosmileSasakiChie'
  'MahonosmileSasakiChie+'
  'SchoolishgirlKisaragiChihaya+'
  'HajiraiotomeKamiyaNao'
  'HajiraiotomeKamiyaNao+'
  'SeifukublueKisaragiChihaya'

# 11
  'RurinoutahimeKisaragiChihaya'
  'RurinoutahimeKisaragiChihaya+'

# 12
  'OffstylenavyWakuiRumi'
  'UruwashinohanayomeWakuiRumi'
  'UruwashinohanayomeWakuiRumi+'
  'SportssaiKomuroChinami'
  'SportssaiKirinoAya'



# パッション
# 2
  'KitamiYuzu'
  'KitamiYuzu+'
  'UedaSuzuho'
  'UedaSuzuho+'

# 3ページ
  'ValentineTakamoriAiko'
  'ValentineTakamoriAiko+'
  'OhanamiOtsukiYui'
  'OhanamiOtsukiYui+'
  'AibaYumi'
  'AibaYumi+'
  'NonomuraSora'
  'NonomuraSora+'

# 4
  'HamakawaAyuna'
  'HamakawaAyuna+'
  'WakabayashiTomoka'
  'WakabayashiTomoka+'
  'JougasakiMika'
  'JougasakiMika+'
  'JougasakiRika'
  'JougasakiRika+'
  'SenzakiEma'
  'SenzakiEma+'
  'HinoAkane'
  'HinoAkane+'
  'MoroboshiKirari'
  'MoroboshiKirari+'
  'TotokiAiri'
  'TotokiAiri+'

# 5
  'Natalia'
  'Natalia+'
  'SomaNatsumi'
  'SomaNatsumi+'
  'MakiharaShiho'
  'MakiharaShiho+'
  'HagiwaraYukiho'
  'HagiwaraYukiho+'
  'FutamiAmi'
  'FutamiAmi+'
  'FutamiMami'
  'FutamiMami+'
  'HoshiiMiki'
  'HoshiiMiki+'
  'MukaiTakumi'
  'MukaiTakumi+'

# 6
  'MinaseIori'
  'MinaseIori+'
  'SeiyaNatalia'
  'SeiyaNatalia+'
  'ShinshunRyuzakiKaoru'
  'ShinshunRyuzakiKaoru+'
  'IchiharaNina'
  'IchiharaNina+'
  'SugisakaUmi'
  'SugisakaUmi+'
  'KitaHinako'
  'KitaHinako+'
  'KitagawaMahiro'
  'KitagawaMahiro+'
  'MaryCochran'
  'MaryCochran+'

# 7
  'KomatsuIbuki'
  'KomatsuIbuki+'
  'ValentineAkagiMiria'
  'ValentineAkagiMiria+'
  'MiyoshiSana'
  'MiyoshiSana+'
  'CathyGraham'
  'CathyGraham+'
  'HinamatsuriUedaSuzuho'
  'HinamatsuriUedaSuzuho+'
  'NambaEmi'
  'NambaEmi+'
  'OhanamiHimekawaYuki'
  'OhanamiHimekawaYuki+'
  'SeifukucollectionKimuraNatsuki'
  'SeifukucollectionKimuraNatsuki+'

# 8
  'SeifukucollectionYaguchiMiu'
  'SeifukucollectionYaguchiMiu+'
  'HamaguchiAyame'
  'HamaguchiAyame+'
  'FlowerbouquetAibaYumi'
  'FlowerbouquetAibaYumi+'
  'ThemeparkSaitoYoko'
  'ThemeparkSaitoYoko+'
  'PajamapartyWakabayashiTomoka'
  'PajamapartyWakabayashiTomoka+'
  'TakabishaojosamaMinaseIori'
  'TakabishaojosamaMinaseIori+'
  'OkubyonatenshiHagiwaraYukiho'
  'OkubyonatenshiHagiwaraYukiho+'
  'ChiisanaeiyuNanjoHikaru'
  'ChiisanaeiyuNanjoHikaru+'

# 9
  'SeiyanoshishaEveSantaclaus'
  'SeiyanoshishaEveSantaclaus+'
  'LovelyprincessMoroboshiKirari'
  'LovelyprincessMoroboshiKirari+'
  'SweetvalentineTotokiAiri'
  'SweetvalentineTotokiAiri+'
  'PowerfulfutagoimotoFutamiAmi'
  'PowerfulfutagoimotoFutamiAmi+'
  'PowerfulfutagoaneFutamiMami'
  'PowerfulfutagoaneFutamiMami+'
  'OtembahinamusumeKitamiYuzu'
  'OtembahinamusumeKitamiYuzu+'
  'CDdebutJougasakiRika'
  'CDdebutJougasakiRika+'
  'MousouohimesamaKitaHinako'
  'MousouohimesamaKitaHinako+'

# 10
  'NemureruhimegimiHoshiiMiki'
  'NemureruhimegimiHoshiiMiki+'
  'SeifukuorangeHoshiiMiki'
  'SainomugendaiHoshiiMiki'
  'SainomugendaiHoshiiMiki+'
  'SeifukublueHagiwaraYukiho'

# 11
  'IyashinotenshiHagiwaraYukiho'
  'IyashinotenshiHagiwaraYukiho+'
  'VeteranTrainer'
  'MasterTrainer'
  'SeiyaTrainer'
  'SeiyaVeteranTrainer'
  'ShinshunTrainer'
  'ShinshunVeteranTrainer'
  'ValentineTrainer'

# 12
  'ValentineVeteranTrainer'

# other
  'FunwarigirlTakamoriAiko'
  'FunwarigirlTakamoriAiko+'
  'AnegohadaMukaiTakumi'
  'AnegohadaMukaiTakumi+'
  'SportssaiSawadaMarina'
  'SportssaiKitagawaMahiro'
  'HappybridalNatalia'

]
